### ISSUE TITLE
1.16.2/3 compability

### ISSUE THREAD

**Issue by puggan** [FaeCraft/SakuraRosea#6]
It would be lovely to have this mod on my 1.16.3-server.

Tried to just [mark it as compatible](https://github.com/puggan/SakuraRosea/commits/1.16/comp-1.16.3), as that works on many other mods, but as this mod is a lot more complex, that didn't work.

When trying to start it on 1.16.3, the error "Cannot inherit from final class" occurs.
On 1.16.2 I instead gets "java.lang.NoSuchFieldError: BIOMES".

**Comment by gdude2002** [comment]
Hey there, thanks for the report.

I know it's not compatible but unfortunately I just haven't had time to
look at it yet. Forge has also been having a hard time with the changes in
1.16.2 - hopefully 1.16.3 works properly at this point.

I'll look into it when I have the time, but it's going to be a while.

**Comment by gdude2002** [comment]
Hiya, apologies for not getting around to this ticket until now.

We're excited to let you know that [we have released a version of SR for 1.16.3 and 1.16.4!](https://www.curseforge.com/minecraft/mc-mods/sakura-rosea/files/3099887)

I note that your fork appears to be unmaintained at this point, but I just wanted to point out that we no longer intend to target Forge and will not accept any pull requests that port to newer versions of Forge.

While GitHub requires that we allow you to create and work on forks of our repos, please bear in mind that the licence applied to the current version of the code would not allow you to share or release any source or binary versions of the project.

**Comment by puggan** [comment]
Thanks for the information, maybe I should convert my server to a fabric version, so I can use this and other fabric only mods.

My fork was only to test out if I could help with the upgrade, but it was out if of my reach, .
And as it no longer have a purpose, I decided to remove my fork.

**Comment by gdude2002** [comment]
No worries at all, I just wanted to make sure you had all the info 👍 

Fabric is growing quite a bit lately — I'm sure you could find alternatives to at least some of your mods.
