### ISSUE TITLE
Biome specific tree coloration working incorrectly

### ISSUE THREAD

**Issue by ghost** [FaeCraft/SakuraRosea#7]
I would recommend looking into how birch and spruce trees have a custom texture and removing the pink foliage overlay from the biome. From what I know, neither tree is affected by the foliage and have their own custom color file. tyyyy

I know this bug is in all versions so far so I hope u can squash it hehe

![2020-10-17_21 11 36](https://user-images.githubusercontent.com/73002835/100533477-dae0f080-31d2-11eb-9059-862dcf9867d9.png)

**Comment by NathnTaylor** [comment]
Are you gonna chase me around on every single social media about this bug....
