### ISSUE TITLE
Leaves not linked to appropriate tool

### ISSUE THREAD

**Issue by AuracleTech** [FaeCraft/SakuraRosea#8]
Leaves are easily broken with a hoe normally, but for this mod's leaves it doesn't work.

**Comment by gdude2002** [comment]
Thanks for the ticket, and sorry for taking so long to get back to you on it.

We'll take a look at this one soon!

**Comment by gdude2002** [comment]
Taking a look at this right now.

It looks like hoes have a hardcoded list of effective blocks, because Mojang. I think I should be able to mixin into this and make it work, though.

**Comment by gdude2002** [comment]
This will be solved in the next release. Thanks for making the issue!
